{% set name = "architector" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/architector-{{ version }}.tar.gz
  sha256: fd70256b54de84deff6f88bdf7aa7e9272f6826d5de0d17ec84523bfadf8f76c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - ase
    - numpy
    - numba
    - py3dmol
    - openbabel
    - scipy
    - pandas
    - xtb-python
    - pynauty
    - openbabel
    - mendeleev
    - tqdm
    - sqlalchemy

test:
  imports:
    - architector
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lanl/Architector
  summary: The architector python package - for 3D inorganometallic complex design.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mgt16-lanl
    - jan-janssen
